# Taller 2  Matematicas avanzadas
Cuaderno principal

# Vinculacion de paquetes/módulos

In [0]:
#Importar de Google Drive
#from google.colab import drive
#drive.mount('/content/drive/My Drive/Colab Notebooks/AdvMath/Taller2/')

#Listar contenido del directorio
#!ls "/content/drive/My Drive/"

In [1]:
#GitHub Git Clone MAT2 donde estan los modulos utilizados
!git clone https://github.com/sampena/MAT2.git
  

Cloning into 'MAT2'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 20 (delta 5), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (20/20), done.


In [0]:
#Imports
import numpy as np
import MAT2.gauss as g


In [5]:
#if __name__ == "__main__":
    A = np.array([[1.,-1.,1.,-1.],[1.,0.,0.,0.],[1.,1.,1.,1.],[1.,2.,4.,8.]])
    b =  np.array([[14.],[4.],[2.],[2.]])
    
    print ("A")
    print (A)

    print ("b")
    print (b)
    
    print("Gauss")
    print (g.GaussJordan(A,b))
    
    print ("A")
    print (A)



A
[[ 1. -1.  1. -1.]
 [ 1.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]]
b
[[14.]
 [ 4.]
 [ 2.]
 [ 2.]]
Gauss
[[ 1.         -1.          1.         -1.        ]
 [ 1.          3.          3.          9.        ]
 [ 1.          0.66666667 -2.         -4.        ]
 [ 1.          0.33333333  1.          2.        ]]
[[ 14.]
 [-12.]
 [ -4.]
 [ -2.]]
[ 4. -5.  4. -1.]
A
[[ 1.         -1.          1.         -1.        ]
 [ 1.          3.          3.          9.        ]
 [ 1.          0.66666667 -2.         -4.        ]
 [ 1.          0.33333333  1.          2.        ]]


Newton Ralson